apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: school-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shathaku/clean-code-microservices.git
    targetRevision: HEAD
    path: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: school-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true