apiVersion: v1
kind: Service
metadata:
  name: school-students-service
spec:
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
  selector:
    app: school-students
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-students-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: school-students
  template:
    metadata:
      labels:
        app: school-students
    spec:
      containers:
      - name: school-students
        image: shathaku/school-students:v2
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_HOST
          value: school-mongo-service
        - name: MONGO_PORT
          value: "27017"
        imagePullPolicy: Never